package br.com.igti.posgraduacao.repositories;

import br.com.igti.posgraduacao.entities.OrquestradorRespostaSolicitarAberturaConta;
import br.com.igti.posgraduacao.entities.OrquestradorSolicitarAberturaConta;

public interface OrquestradorSolicitarAberturaContaRepository {
    OrquestradorRespostaSolicitarAberturaConta solicitarAberturaDeConta(OrquestradorSolicitarAberturaConta orquestradorSolicitarAberturaConta);
}
