spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/camunda
    username: dbcamundaadmin
    password: dbcamundapassword

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo

# custom path for swagger-ui
springdoc:
  swagger-ui:
    path: /swaggerui.html
    operationsSorter: alpha
    tagsSorter: alpha
  # custom path for api docs
  api-docs:
    path: /api-docs

#Feign Client
servicos:
  fraude:
    url: http://localhost:8051/service-fraude/api/v1/fraude


feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 10000
      fraude:
        connectTimeout: 40000
        readTimeout: 10000

