spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/camunda
    username: dbcamundaadmin
    password: dbcamundapassword

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo

# custom path for swagger-ui
springdoc:
  swagger-ui:
    path: /swaggerui.html
    operationsSorter: alpha
    tagsSorter: alpha
  # custom path for api docs
  api-docs:
    path: /api-docs


#Url
servicos:
  fraude:
    url: http://localhost:8051/service-fraude/api/v1/fraude
  cadastropositivo:
    url: http://localhost:8021/service-cadastro-positivo/api/v1/
  cadastronegativo:
    url: http://localhost:8031/service-cadastro-negativo/api/v1/
  cadastrocliente:
    url: http://localhost:8041/service-cliente/api/v1/
  cliente:
    notifica:
      url: http://localhost:8061/service-hub-mensagens/api/v1/
  gerente:
    notifica:
      url: http://localhost:8061/service-hub-mensagens/api/v1/
  prospecto:
    notifica:
      url: http://localhost:8061/service-hub-mensagens/api/v1/



#Feign Client
feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 10000
      fraude:
        connectTimeout: 40000
        readTimeout: 10000

