spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: db_hub_mensagens

  mail:
    host: mtp.gmail.com
    port: 587
    username: email@gmail.com
    password: teste
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          # SSL, post 465
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

app:
  groupId: '@project.groupId@'
  name: '@project.artifactId@'
  version: '@project.version@'


# custom path for swagger-ui
springdoc:
  swagger-ui:
    path: /swaggerui.html
    operationsSorter: alpha
    tagsSorter: alpha

  # custom path for api docs
  api-docs:
    path: /api-docs

